# Golang Backend Dockerfile with SOLID principles
FROM golang:1.23.2-alpine
WORKDIR /app

# Install necessary packages for CGO
RUN apk add --no-cache gcc musl-dev

# Copia os arquivos necessários para instalar as dependências
COPY backend-go/go.mod backend-go/go.sum ./
RUN go mod download

# Copia o restante do código e compila
COPY backend-go/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

EXPOSE 8081
CMD ["./main"]
